field.toString().trim()
fix error 

caused by: TypeError: field.trim is not a function

PRE-MONOREPO-COMMIT: https://github.com/hi-ogawa/demo-init-monorepo--node-csv-parse/commit/f39c4843fa8bc5e19b8bdf05213b5a41cc1c9a92